services:
    novelya-back:
        build:
            context: .
            dockerfile: Dockerfile.prod
        image: novelya-back:prod
        container_name: novelya-back-prod
        ports:
            - "3000:3000"
        env_file: .env.prod
        environment:
            - TZ=Europe/Paris
            - NODE_ENV=production
        depends_on:
            mongodb:
                condition: service_healthy
        volumes:
            - ./public/covers:/app/public/covers
        restart: unless-stopped

    mongodb:
        image: mongo:8
        container_name: novelya-mongodb-prod
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongodb_prod_data:/data/db
            - ./src/config/init-db.js:/docker-entrypoint-initdb.d/init.js
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

volumes:
    mongodb_prod_data:
